version: "3"

services:
  bot:
    build: .
    restart: always
    env_file:
      - ./env/bot.env
      - ./env/posgres.env
    environment:
    - POSTGRES_HOST=db

  db:
    image: postgres
    restart: always
    env_file:
      - ./env/posgres.env

  adminer:
    profiles:
      - "debug"
    image: adminer
    restart: always
    ports:
      - 8080:8080
